import Head from "next/head";

export default function Seo({ title = '애플'  } ) {
    
    return <>
        {/* <Head> */}
            <title>{title}</title>
            <meta name="description" content="Generated by create next app" />
            {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
            <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" /> 
            {/* 테마 색상/파비콘/manifest 파일 지정 */}
            <link rel="icon" href="/favicon.ico" />
            <meta name="theme-color" content="#cfffb9" />
            {/* <link rel="manifest" href="/manifest.json" />  */}
        {/* </Head> */}
    </>
}

// next v13 이후 신버전에서 defaultProps 삭제 예정 dfault parameters 사용 권고

// Seo.defaultProps = {
//     title: 'Super'
// }
